services:
  api:
    build: .
    container_name: api
    working_dir: /src/rest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ${ADBREW_CODEBASE_PATH}:/src

  app:
    build: .
    container_name: app
    working_dir: /src/app
    command: bash -c "yarn install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ${ADBREW_CODEBASE_PATH}:/src
      - adbrew_app_node_modules:/src/app/node_modules

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${ADBREW_CODEBASE_PATH}/db:/data/db
    command: /usr/bin/mongod --bind_ip 0.0.0.0

volumes:
  adbrew_app_node_modules: